#robin.elasticjob.zk:
#  servers: 192.168.109.144:2181,192.168.109.144:2182,192.168.109.144:2183
#  namespace: test
# 9200端口是用来让HTTP REST API来访问ElasticSearch，而9300端口是传输层监听的默认端口
elasticsearch:
  ip: 192.168.109.144
  port: 9300
  pool: 5
#注意cluster.name需要与config/elasticsearch.yml中的cluster.name一致
  cluster-name: my-application